---
apiVersion: v1
data:
  database: <db name>
  host: <db host>
  password: <db paswword>
  port: NTQzMg== # 5432
  provider: YXdz  # aws
  type: cG9zdGdyZXNxbA==  # postgresql
  username: <db username>
kind: Secret
metadata:
  name: db-where-for-dinner
type: connection.crossplane.io/v1alpha1
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: db-where-for-dinner
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: db-where-for-dinner