---
apiVersion: bitnami.caching.tanzu.vmware.com/v1alpha1
kind: RedisCluster
metadata:
  name: cache-where-for-dinner
spec:
  storageGB: 1
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: cache-where-for-dinner
spec:
  ref:
    apiVersion: bitnami.caching.tanzu.vmware.com/v1alpha1
    kind: RedisCluster
    name: cache-where-for-dinner