apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
spec:
  virtualhost:
    fqdn: <UPDATE ME>
  routes:
    - conditions:
        - prefix: /
      services:
        - name: spring-cloud-gateway
          port: 80
