---
apiVersion: bitnami.messaging.tanzu.vmware.com/v1alpha1
kind: RabbitmqCluster
metadata:
  name: msgbroker-where-for-dinner
spec:
  replicas: 1
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: msgbroker-where-for-dinner
spec:
  ref:
    apiVersion: bitnami.messaging.tanzu.vmware.com/v1alpha1
    kind: RabbitmqCluster
    name: msgbroker-where-for-dinner
---
apiVersion: bitnami.database.tanzu.vmware.com/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: db-where-for-dinner
spec:
  storageGB: 1
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: db-where-for-dinner
spec:
  ref:
    apiVersion: bitnami.database.tanzu.vmware.com/v1alpha1
    kind: PostgreSQLInstance
    name: db-where-for-dinner
---
apiVersion: bitnami.caching.tanzu.vmware.com/v1alpha1
kind: RedisCluster
metadata:
  name: cache-where-for-dinner
spec:
  storageGB: 1
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: cache-where-for-dinner
spec:
  ref:
    apiVersion: bitnami.caching.tanzu.vmware.com/v1alpha1
    kind: RedisCluster
    name: cache-where-for-dinner