---
apiVersion: v1
data:
  addresses: <broker address including "amqps:" and port>
  password: <broker password>
  provider: YXdz # aws
  type: cmFiYml0bXE= # rabbitmq
  username: <broker username>
kind: Secret
metadata:
  name: msgbroker-where-for-dinner-region-1
type: connection.crossplane.io/v1alpha1
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: msgbroker-where-for-dinner
spec:
  ref:
    apiVersion: bitnami.messaging.tanzu.vmware.com/v1alpha1
    kind: RabbitmqCluster
    name: msgbroker-where-for-dinner-region-1